version: '3'

services:
  server:
    build: .
    image: server:0.0.1
    container_name: server
    networks:
      - webnet
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:v2.40.7
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - webnet

  grafana:
    image: grafana/grafana:9.4.2
    container_name: grafana
    volumes:
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - webnet
    ports:
      - "3000:3000"

networks:
  webnet:
    driver: bridge
